name: Android Build

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Changed gradlew file permissions
        run: chmod +x ./gradlew
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Run Tests Build
      - name: Run gradle tests
        run: ./gradlew test
         
      - name: Build App
        run: ./gradlew assemble
        
