name: Project CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build App
        run: ./gradlew assemble

      - name: Changed gradlew file permissions
        run: chmod +x ./gradlew
        
